# Generated by Django 5.2.6 on 2025-09-22 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0004_enforce_slug_not_null"),
        ("courses", "0003_codingchallenge_entrypoint_filename_and_more"),
        ("students", "0004_lessoncomment_studentxpevent_studentcertificate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyEngagementSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("active_students", models.PositiveIntegerField(default=0)),
                ("new_students", models.PositiveIntegerField(default=0)),
                ("lessons_viewed", models.PositiveIntegerField(default=0)),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("courses_completed", models.PositiveIntegerField(default=0)),
                ("assessments_completed", models.PositiveIntegerField(default=0)),
                ("comments_posted", models.PositiveIntegerField(default=0)),
                ("xp_earned", models.IntegerField(default=0)),
                ("certificates_issued", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="LearningEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("lesson_viewed", "Lesson viewed"),
                            ("lesson_completed", "Lesson completed"),
                            ("course_completed", "Course completed"),
                            ("assessment_started", "Assessment started"),
                            ("assessment_completed", "Assessment completed"),
                            ("xp_awarded", "XP awarded"),
                            ("comment_created", "Comment created"),
                            ("announcement_published", "Announcement published"),
                            ("notification_read", "Notification read"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("backend", "Backend"), ("frontend", "Frontend")],
                        default="backend",
                        max_length=32,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="courses.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="students.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="analytics_l_event_t_23d46c_idx",
                    ),
                    models.Index(
                        fields=["student", "occurred_at"],
                        name="analytics_l_student_c4e368_idx",
                    ),
                ],
            },
        ),
    ]
