# Generated by Django 4.2.7 on 2025-09-25 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyEngagementSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("active_students", models.PositiveIntegerField(default=0)),
                ("new_students", models.PositiveIntegerField(default=0)),
                ("lessons_viewed", models.PositiveIntegerField(default=0)),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("courses_completed", models.PositiveIntegerField(default=0)),
                ("assessments_completed", models.PositiveIntegerField(default=0)),
                ("comments_posted", models.PositiveIntegerField(default=0)),
                ("xp_earned", models.IntegerField(default=0)),
                ("certificates_issued", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="LearningEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("lesson_viewed", "Lesson viewed"),
                            ("lesson_completed", "Lesson completed"),
                            ("course_completed", "Course completed"),
                            ("assessment_started", "Assessment started"),
                            ("assessment_completed", "Assessment completed"),
                            ("xp_awarded", "XP awarded"),
                            ("comment_created", "Comment created"),
                            ("announcement_published", "Announcement published"),
                            ("notification_read", "Notification read"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("backend", "Backend"), ("frontend", "Frontend")],
                        default="backend",
                        max_length=32,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
