# Generated by Django 4.2.7 on 2025-09-25 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningevent",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to="assessments.assessment",
            ),
        ),
    ]
