# Generated by Django 4.2.7 on 2025-09-25 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
        ("courses", "0001_initial"),
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningevent",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="learningevent",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="learningevent",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_events",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="learningevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="learningevent",
            index=models.Index(
                fields=["event_type", "occurred_at"],
                name="analytics_l_event_t_23d46c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningevent",
            index=models.Index(
                fields=["student", "occurred_at"], name="analytics_l_student_c4e368_idx"
            ),
        ),
    ]
