# Generated by Django 5.2.6 on 2025-09-22 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("courses", "0003_codingchallenge_entrypoint_filename_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="studentquizattempt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="studentquizattempt",
            old_name="attempted_at",
            new_name="started_at",
        ),
        migrations.AddField(
            model_name="assessment",
            name="available_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="available_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="certificate_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="assessment",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="is_practice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="issues_certificate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="max_attempts",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reward_badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="courses.challengebadge",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reward_xp",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="assessment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assessment",
            name="time_limit_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="studentquizattempt",
            name="awarded_xp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentquizattempt",
            name="completed_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentquizattempt",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentquizattempt",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentquizattempt",
            name="percentage_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assessment",
            name="passing_score",
            field=models.IntegerField(
                help_text="Percentage threshold required to pass"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("free_response", "Free Response"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("assessment", "order")},
        ),
    ]
