# Generated by Django 4.2.7 on 2025-09-25 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("courses", "0001_initial"),
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentquizattempt",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reward_badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="courses.challengebadge",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("assessment", "order")},
        ),
    ]
