# Generated by Django 5.1.13 on 2025-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="availability",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="last_activity_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="learning_goals",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="preferred_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("hybrid", "Hybrid"),
                ],
                default="hybrid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="streak_days",
            field=models.IntegerField(default=0),
        ),
    ]
