# Generated by Django 5.2.6 on 2025-09-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="accessibility_preferences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="student",
            name="allow_offline_downloads",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="interest_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="student",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="studentlesson",
            name="last_position_seconds",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="studentlesson",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
