# Generated by Django 5.1.13 on 2025-11-02 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="spotlight",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitle",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="track",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Web", "Web Development"),
                    ("Data", "Data Science"),
                    ("Design", "Design"),
                ],
                default="Web",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("video", "Video Lesson"),
                    ("interactive", "Interactive Coding"),
                    ("reading", "Reading Material"),
                    ("quiz", "Quiz"),
                    ("project", "Project"),
                ],
                default="video",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of instructor"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Lead Instructor, Teaching Assistant",
                        max_length=100,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Instructor bio for this course"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_instructors",
                        to="courses.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("course", "instructor")},
            },
        ),
        migrations.CreateModel(
            name="LessonVersionMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marker_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "label",
                    models.CharField(help_text="Label for this marker", max_length=255),
                ),
                (
                    "timecode",
                    models.FloatField(help_text="Time in seconds from start of video"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "marker_type",
                    models.CharField(
                        choices=[
                            ("chapter", "Chapter Marker"),
                            ("note", "Note"),
                            ("highlight", "Highlight"),
                            ("bookmark", "Bookmark"),
                        ],
                        default="chapter",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_markers",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "timecode"],
                "unique_together": {("lesson", "timecode")},
            },
        ),
    ]
