# Generated by Django 5.2.6 on 2025-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_course_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingchallenge",
            name="entrypoint_filename",
            field=models.CharField(default="main.py", max_length=255),
        ),
        migrations.AddField(
            model_name="codingchallenge",
            name="hints",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="codingchallenge",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="codingchallenge",
            name="solution_files",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="codingchallenge",
            name="starter_files",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="codingchallenge",
            name="test_cases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="codingchallenge",
            name="time_limit_seconds",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
